# Generated by Django 6.0.2 on 2026-03-12 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0004_asset_geofence_enabled_asset_geofence_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('requester_phone', models.CharField(max_length=20)),
                ('purpose', models.TextField(help_text='Purpose or reason for the checkout.')),
                ('intended_location', models.CharField(help_text='Where the asset will be used.', max_length=300)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_checkout_date', models.DateField(help_text='Requested checkout date.')),
                ('requested_return_date', models.DateField(help_text='Requested return date.')),
                ('actual_checkout_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHECKED_OUT', 'Checked Out'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('condition_at_checkout', models.TextField(blank=True, help_text='Asset condition when checked out.')),
                ('condition_at_return', models.TextField(blank=True, help_text='Asset condition when returned.', null=True)),
                ('damage_reported', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('damage_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated repair or replacement cost.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Admin-only notes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checkouts', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='assets.asset')),
                ('checked_out_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_checkouts', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_requests', to='accounts.department')),
                ('returned_to_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout Request',
                'verbose_name_plural': 'Checkout Requests',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='checkouts.checkoutrequest')),
            ],
            options={
                'verbose_name': 'Checkout History',
                'verbose_name_plural': 'Checkout Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.FloatField(help_text='GPS accuracy in meters.')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters.', null=True)),
                ('speed_kmh', models.FloatField(blank=True, help_text='Speed in km/h.', null=True)),
                ('heading_degrees', models.FloatField(blank=True, help_text='Direction in degrees.', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery percentage (0-100).', null=True)),
                ('is_inside_geofence', models.BooleanField(default=True)),
                ('distance_from_center_meters', models.FloatField(blank=True, help_text='Distance from the configured geofence center.', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='checkouts.checkoutrequest')),
            ],
            options={
                'verbose_name': 'GPS Location',
                'verbose_name_plural': 'GPS Locations',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('GEOFENCE_EXIT', 'Asset Left Campus'), ('GEOFENCE_ENTRY', 'Asset Returned to Campus'), ('LOW_BATTERY', 'GPS Device Low Battery'), ('SIGNAL_LOST', 'GPS Signal Lost')], max_length=20)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_alert_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='checkouts.checkoutrequest')),
                ('gps_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='checkouts.gpslocation')),
            ],
            options={
                'verbose_name': 'Geofence Alert',
                'verbose_name_plural': 'Geofence Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkoutrequest',
            index=models.Index(fields=['request_number'], name='checkouts_c_request_477105_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutrequest',
            index=models.Index(fields=['status'], name='checkouts_c_status_b2be37_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutrequest',
            index=models.Index(fields=['requested_by'], name='checkouts_c_request_8f5efb_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutrequest',
            index=models.Index(fields=['requested_checkout_date', 'requested_return_date'], name='checkouts_c_request_a59423_idx'),
        ),
        migrations.AddIndex(
            model_name='checkouthistory',
            index=models.Index(fields=['checkout', 'changed_at'], name='checkouts_c_checkou_df64dd_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['checkout', 'recorded_at'], name='checkouts_g_checkou_577b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencealert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='checkouts_g_alert_t_a6e7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencealert',
            index=models.Index(fields=['created_at'], name='checkouts_g_created_89c88e_idx'),
        ),
    ]
