# Generated by Django 6.0.2 on 2026-03-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Unique identifier (e.g., IUIU-PC-001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(help_text='Physical location (e.g., Room 204, Server Room)', max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('FAULTY', 'Faulty'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_tag'], name='assets_asse_asset_t_42b762_idx'), models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'), models.Index(fields=['department'], name='assets_asse_departm_eda949_idx')],
            },
        ),
    ]
