# Generated by Django 6.0.2 on 2026-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_software_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='geofence_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='geofence_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Campus center latitude for geofence checks.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='geofence_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Campus center longitude for geofence checks.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=500, help_text='Allowed geofence radius in meters.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='gps_device_id',
            field=models.CharField(blank=True, help_text='GPS tracker device identifier.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_gps_tracker',
            field=models.BooleanField(default=False, help_text='Is a GPS tracker installed on this asset?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_portable',
            field=models.BooleanField(default=False, help_text='Can this asset be checked out for temporary use?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='max_checkout_days',
            field=models.PositiveIntegerField(default=7, help_text='Maximum number of days this asset can be checked out.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Does this asset require approval before checkout?'),
        ),
    ]
