# Generated by Django 6.0.2 on 2026-03-13 06:51

from datetime import date

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LEGACY_STATUS_MAP = {
    "ACTIVE": "available",
    "UNDER_MAINTENANCE": "maintenance",
    "FAULTY": "maintenance",
    "RETIRED": "retired",
    "IN_STORAGE": "available",
    "DISPOSED": "retired",
}


def _normalize_location_name(value):
    cleaned = " ".join((value or "").split())
    return cleaned or "Unspecified"


def migrate_legacy_asset_data(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    AssetAssignment = apps.get_model("assets", "AssetAssignment")
    AssetLocationHistory = apps.get_model("assets", "AssetLocationHistory")
    AssetType = apps.get_model("assets", "AssetType")
    ComputerAsset = apps.get_model("assets", "ComputerAsset")
    InstalledSoftware = apps.get_model("assets", "InstalledSoftware")
    Location = apps.get_model("assets", "Location")
    MaintenanceRecord = apps.get_model("assets", "MaintenanceRecord")
    Software = apps.get_model("assets", "Software")
    db_alias = schema_editor.connection.alias

    for software in Software.objects.using(db_alias).all():
        software.name = software.name or getattr(software, "software_name", None) or f"Software {software.pk}"
        software.vendor = software.vendor or getattr(software, "publisher", None) or ""
        software.version = software.version or ""
        software.save(update_fields=["name", "vendor", "version"])

    location_cache = {}

    def get_location(raw_name):
        normalized = _normalize_location_name(raw_name)
        key = (normalized, "", "")
        if key not in location_cache:
            location_cache[key], _ = Location.objects.using(db_alias).get_or_create(
                name=normalized,
                building="",
                room="",
            )
        return location_cache[key]

    assets_with_location_history = set()
    for history in AssetLocationHistory.objects.using(db_alias).all():
        assets_with_location_history.add(history.asset_id)
        location_name = getattr(history, "new_location", "") or getattr(history, "previous_location", "")
        history.location_id = get_location(location_name).id
        history.notes = getattr(history, "reason", "") or ""
        history.save(update_fields=["location", "notes"])

    asset_type_cache = {}
    computer_type_by_asset_id = {
        computer.asset_id: computer.computer_type.replace("_", " ").title()
        for computer in ComputerAsset.objects.using(db_alias).all()
    }

    def get_asset_type(category_id, type_name):
        key = (category_id, type_name)
        if key not in asset_type_cache:
            asset_type_cache[key], _ = AssetType.objects.using(db_alias).get_or_create(
                category_id=category_id,
                name=type_name,
            )
        return asset_type_cache[key]

    for asset in Asset.objects.using(db_alias).all():
        legacy_status = asset.status
        mapped_status = LEGACY_STATUS_MAP.get(legacy_status, "available")
        if asset.assigned_to_id and mapped_status == "available":
            mapped_status = "assigned"

        asset.asset_type_id = get_asset_type(
            asset.category_id,
            computer_type_by_asset_id.get(asset.id, "General"),
        ).id
        asset.status = mapped_status
        asset.is_active = mapped_status not in {"retired", "lost"}
        asset.serial_number = asset.serial_number or ""
        asset.save(update_fields=["asset_type", "status", "is_active", "serial_number"])

        if asset.assigned_to_id and not AssetAssignment.objects.using(db_alias).filter(
            asset_id=asset.id,
            user_id=asset.assigned_to_id,
            returned_date__isnull=True,
        ).exists():
            AssetAssignment.objects.using(db_alias).create(
                asset_id=asset.id,
                user_id=asset.assigned_to_id,
                assigned_date=asset.purchase_date or asset.created_at.date(),
                issued_by_id=asset.created_by_id,
                notes="Migrated from legacy assigned_to field.",
            )

        if asset.id not in assets_with_location_history and getattr(asset, "current_location", ""):
            AssetLocationHistory.objects.using(db_alias).create(
                asset_id=asset.id,
                location_id=get_location(asset.current_location).id,
                moved_by_id=asset.created_by_id,
                moved_at=asset.updated_at,
                notes="Migrated from legacy current_location field.",
            )

        if legacy_status in {"UNDER_MAINTENANCE", "FAULTY"} and not MaintenanceRecord.objects.using(
            db_alias
        ).filter(asset_id=asset.id).exists():
            MaintenanceRecord.objects.using(db_alias).create(
                asset_id=asset.id,
                issue_description=f"Migrated from legacy status {legacy_status}.",
                maintenance_type="repair" if legacy_status == "FAULTY" else "inspection",
                start_date=asset.updated_at.date() if asset.updated_at else asset.purchase_date or date.today(),
                status="open",
                notes="Created during the asset schema migration.",
            )

    computers = ComputerAsset.objects.using(db_alias).select_related("asset").prefetch_related("software")
    for computer in computers:
        installed_date = computer.asset.purchase_date or computer.asset.created_at.date()
        for software in computer.software.all():
            InstalledSoftware.objects.using(db_alias).get_or_create(
                asset_id=computer.asset_id,
                software_id=software.id,
                defaults={
                    "installed_date": installed_date,
                    "installed_by_id": computer.asset.created_by_id,
                    "notes": "Migrated from legacy computer software records.",
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_asset_geofence_enabled_asset_geofence_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(name="AssetActivityLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("action", models.CharField(max_length=200)), ("timestamp", models.DateTimeField(auto_now_add=True)), ("description", models.TextField(blank=True))], options={"ordering": ["-timestamp"]}),
        migrations.CreateModel(name="AssetAssignment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("assigned_date", models.DateField()), ("expected_return", models.DateField(blank=True, null=True)), ("returned_date", models.DateField(blank=True, null=True)), ("notes", models.TextField(blank=True))], options={"ordering": ["-assigned_date"]}),
        migrations.CreateModel(name="AssetAttribute", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("field_type", models.CharField(choices=[("text", "Text"), ("number", "Number"), ("date", "Date"), ("boolean", "Boolean")], default="text", max_length=20)), ("required", models.BooleanField(default=False)), ("help_text", models.CharField(blank=True, max_length=255))], options={"ordering": ["category__name", "name"]}),
        migrations.CreateModel(name="AssetAttributeValue", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("value", models.TextField())], options={"ordering": ["attribute__name"]}),
        migrations.CreateModel(name="AssetAudit", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("audit_date", models.DateField()), ("notes", models.TextField(blank=True))], options={"ordering": ["-audit_date", "-id"]}),
        migrations.CreateModel(name="AssetAuditItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("found", "Found"), ("missing", "Missing"), ("damaged", "Damaged"), ("relocated", "Relocated")], max_length=50)), ("notes", models.TextField(blank=True))], options={"ordering": ["asset__asset_tag"]}),
        migrations.CreateModel(name="AssetDepreciation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("purchase_cost", models.DecimalField(decimal_places=2, max_digits=12)), ("useful_life_years", models.PositiveIntegerField()), ("salvage_value", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("depreciation_method", models.CharField(choices=[("straight_line", "Straight Line")], default="straight_line", max_length=50)), ("start_date", models.DateField())], options={"ordering": ["asset__asset_tag"]}),
        migrations.CreateModel(name="AssetPurchase", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("purchase_order", models.CharField(max_length=100)), ("invoice_number", models.CharField(blank=True, max_length=100)), ("purchase_date", models.DateField()), ("total_cost", models.DecimalField(decimal_places=2, max_digits=12))], options={"ordering": ["-purchase_date", "-id"]}),
        migrations.CreateModel(name="AssetType", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100))], options={"ordering": ["category__name", "name"]}),
        migrations.CreateModel(name="InstalledSoftware", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("installed_date", models.DateField(blank=True, null=True)), ("notes", models.TextField(blank=True))], options={"ordering": ["asset__asset_tag", "software__name"]}),
        migrations.CreateModel(name="Location", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("building", models.CharField(blank=True, max_length=150)), ("room", models.CharField(blank=True, max_length=50)), ("description", models.TextField(blank=True))], options={"ordering": ["name", "building", "room"]}),
        migrations.CreateModel(name="MaintenanceRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("issue_description", models.TextField()), ("maintenance_type", models.CharField(choices=[("repair", "Repair"), ("upgrade", "Upgrade"), ("inspection", "Inspection")], max_length=100)), ("start_date", models.DateField()), ("end_date", models.DateField(blank=True, null=True)), ("technician", models.CharField(blank=True, max_length=150)), ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In Progress"), ("completed", "Completed")], default="open", max_length=50)), ("notes", models.TextField(blank=True))], options={"ordering": ["-start_date", "-id"]}),
        migrations.CreateModel(name="Supplier", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150, unique=True)), ("contact_email", models.EmailField(blank=True, max_length=254)), ("phone", models.CharField(blank=True, max_length=50)), ("address", models.TextField(blank=True))], options={"ordering": ["name"]}),
        migrations.AlterModelOptions(name="asset", options={"ordering": ["asset_tag"]}),
        migrations.AlterModelOptions(name="assetlocationhistory", options={"ordering": ["-moved_at"]}),
        migrations.AlterModelOptions(name="software", options={"ordering": ["name", "version"]}),
        migrations.RemoveConstraint(model_name="software", name="assets_sw_catalog_uniq"),
        migrations.RemoveIndex(model_name="asset", name="assets_asse_asset_t_42b762_idx"),
        migrations.RemoveIndex(model_name="asset", name="assets_asse_status_347ce9_idx"),
        migrations.RemoveIndex(model_name="asset", name="assets_asse_departm_eda949_idx"),
        migrations.RemoveIndex(model_name="asset", name="assets_asse_categor_7db38a_idx"),
        migrations.RemoveField(model_name="assetcategory", name="created_at"),
        migrations.RemoveField(model_name="assetcategory", name="default_depreciation_rate"),
        migrations.RemoveField(model_name="assetlocationhistory", name="created_at"),
        migrations.AddField(model_name="asset", name="is_active", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="assetlocationhistory", name="notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="software", name="name", field=models.CharField(blank=True, max_length=150, null=True)),
        migrations.AddField(model_name="software", name="vendor", field=models.CharField(blank=True, max_length=150)),
        migrations.AlterField(model_name="asset", name="asset_tag", field=models.CharField(max_length=50, null=True, unique=True)),
        migrations.AlterField(model_name="asset", name="purchase_cost", field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
        migrations.AlterField(model_name="asset", name="serial_number", field=models.CharField(blank=True, max_length=200)),
        migrations.AlterField(model_name="asset", name="status", field=models.CharField(choices=[("available", "Available"), ("assigned", "Assigned"), ("maintenance", "Maintenance"), ("reserved", "Reserved"), ("retired", "Retired"), ("lost", "Lost")], default="available", max_length=20)),
        migrations.AlterField(model_name="assetcategory", name="description", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="assetlocationhistory", name="moved_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_moves", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="assetactivitylog", name="asset", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activity_logs", to="assets.asset")),
        migrations.AddField(model_name="assetactivitylog", name="performed_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_activity_logs", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="assetassignment", name="asset", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="assets.asset")),
        migrations.AddField(model_name="assetassignment", name="issued_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issued_asset_assignments", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="assetassignment", name="user", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="asset_assignments", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="assetattribute", name="category", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="assets.assetcategory")),
        migrations.AddField(model_name="assetattributevalue", name="asset", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attribute_values", to="assets.asset")),
        migrations.AddField(model_name="assetattributevalue", name="attribute", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="values", to="assets.assetattribute")),
        migrations.AddField(model_name="assetaudit", name="conducted_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_audits_conducted", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="assetaudititem", name="asset", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_items", to="assets.asset")),
        migrations.AddField(model_name="assetaudititem", name="audit", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="assets.assetaudit")),
        migrations.AddField(model_name="assetdepreciation", name="asset", field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="depreciation", to="assets.asset")),
        migrations.AddField(model_name="asset", name="purchase", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assets", to="assets.assetpurchase")),
        migrations.AddField(model_name="assettype", name="category", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="types", to="assets.assetcategory")),
        migrations.AddField(model_name="asset", name="asset_type", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="assets.assettype")),
        migrations.AddField(model_name="installedsoftware", name="asset", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="installed_software", to="assets.asset")),
        migrations.AddField(model_name="installedsoftware", name="installed_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="software_installations", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="installedsoftware", name="software", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="installations", to="assets.software")),
        migrations.AlterUniqueTogether(name="location", unique_together={("name", "building", "room")}),
        migrations.AddField(model_name="assetlocationhistory", name="location", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="asset_history", to="assets.location")),
        migrations.AddField(model_name="maintenancerecord", name="asset", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_records", to="assets.asset")),
        migrations.AddField(model_name="assetpurchase", name="supplier", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchases", to="assets.supplier")),
        migrations.RunPython(migrate_legacy_asset_data, migrations.RunPython.noop),
        migrations.AlterField(model_name="software", name="version", field=models.CharField(blank=True, max_length=100)),
        migrations.AlterUniqueTogether(name="software", unique_together={("name", "version", "vendor")}),
        migrations.RemoveField(model_name="assetlocationhistory", name="new_department"),
        migrations.RemoveField(model_name="assetlocationhistory", name="new_location"),
        migrations.RemoveField(model_name="assetlocationhistory", name="previous_department"),
        migrations.RemoveField(model_name="assetlocationhistory", name="previous_location"),
        migrations.RemoveField(model_name="assetlocationhistory", name="reason"),
        migrations.RemoveField(model_name="assetstatushistory", name="asset"),
        migrations.RemoveField(model_name="assetstatushistory", name="changed_by"),
        migrations.RemoveField(model_name="computerasset", name="asset"),
        migrations.RemoveField(model_name="computerasset", name="software"),
        migrations.DeleteModel(name="AssetStatusHistory"),
        migrations.DeleteModel(name="ComputerAsset"),
        migrations.RemoveField(model_name="asset", name="assigned_to"),
        migrations.RemoveField(model_name="asset", name="created_by"),
        migrations.RemoveField(model_name="asset", name="current_location"),
        migrations.RemoveField(model_name="asset", name="depreciation_rate"),
        migrations.RemoveField(model_name="asset", name="geofence_enabled"),
        migrations.RemoveField(model_name="asset", name="geofence_latitude"),
        migrations.RemoveField(model_name="asset", name="geofence_longitude"),
        migrations.RemoveField(model_name="asset", name="geofence_radius_meters"),
        migrations.RemoveField(model_name="asset", name="gps_device_id"),
        migrations.RemoveField(model_name="asset", name="has_gps_tracker"),
        migrations.RemoveField(model_name="asset", name="image"),
        migrations.RemoveField(model_name="asset", name="is_portable"),
        migrations.RemoveField(model_name="asset", name="last_serviced"),
        migrations.RemoveField(model_name="asset", name="manufacturer"),
        migrations.RemoveField(model_name="asset", name="max_checkout_days"),
        migrations.RemoveField(model_name="asset", name="model"),
        migrations.RemoveField(model_name="asset", name="next_service_due"),
        migrations.RemoveField(model_name="asset", name="notes"),
        migrations.RemoveField(model_name="asset", name="requires_approval"),
        migrations.RemoveField(model_name="software", name="created_at"),
        migrations.RemoveField(model_name="software", name="license_expiry"),
        migrations.RemoveField(model_name="software", name="license_key"),
        migrations.RemoveField(model_name="software", name="license_type"),
        migrations.RemoveField(model_name="software", name="notes"),
        migrations.RemoveField(model_name="software", name="publisher"),
        migrations.RemoveField(model_name="software", name="software_name"),
        migrations.RemoveField(model_name="software", name="updated_at"),
        migrations.AlterUniqueTogether(name="assetattribute", unique_together={("category", "name")}),
        migrations.AlterUniqueTogether(name="assetattributevalue", unique_together={("asset", "attribute")}),
        migrations.AlterUniqueTogether(name="assetaudititem", unique_together={("audit", "asset")}),
        migrations.AlterUniqueTogether(name="assettype", unique_together={("category", "name")}),
        migrations.AlterUniqueTogether(name="installedsoftware", unique_together={("asset", "software")}),
    ]
