# Generated by Django 6.0.2 on 2026-03-13 08:23

from decimal import Decimal

from django.db import migrations


def backfill_asset_depreciation_records(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    AssetDepreciation = apps.get_model("assets", "AssetDepreciation")
    db_alias = schema_editor.connection.alias

    assets = Asset.objects.using(db_alias).filter(
        purchase_cost__isnull=False,
        purchase_date__isnull=False,
    )

    for asset in assets.iterator():
        AssetDepreciation.objects.using(db_alias).get_or_create(
            asset_id=asset.id,
            defaults={
                "purchase_cost": asset.purchase_cost,
                "useful_life_years": 5,
                "salvage_value": Decimal("0.00"),
                "depreciation_method": "straight_line",
                "start_date": asset.purchase_date,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_make_asset_type_location_and_software_name_required"),
    ]

    operations = [
        migrations.RunPython(
            backfill_asset_depreciation_records,
            migrations.RunPython.noop,
        ),
    ]
