# Generated by Django 6.0.2 on 2026-03-13 12:14

from django.db import migrations, models


CANONICAL_CATEGORY_NAMES = [
    "Computers",
    "Networking",
    "Furniture",
    "Printers",
    "Consumables",
    "Projectors",
    "Others",
]

NORMALIZED_CATEGORY_MAP = {
    "computer": "Computers",
    "computers": "Computers",
    "desktop": "Computers",
    "laptop": "Computers",
    "network": "Networking",
    "networking": "Networking",
    "router": "Networking",
    "switch": "Networking",
    "furniture": "Furniture",
    "printer": "Printers",
    "printers": "Printers",
    "consumable": "Consumables",
    "consumables": "Consumables",
    "projector": "Projectors",
    "projectors": "Projectors",
    "other": "Others",
    "others": "Others",
}


def _canonical_name(raw_name):
    cleaned = " ".join((raw_name or "").split()).lower()
    return NORMALIZED_CATEGORY_MAP.get(cleaned, "Others")


def normalize_asset_categories(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    AssetAttribute = apps.get_model("assets", "AssetAttribute")
    AssetAttributeValue = apps.get_model("assets", "AssetAttributeValue")
    AssetCategory = apps.get_model("assets", "AssetCategory")
    AssetType = apps.get_model("assets", "AssetType")
    db_alias = schema_editor.connection.alias

    categories = list(AssetCategory.objects.using(db_alias).order_by("id"))
    for category in categories:
        target_name = _canonical_name(category.name)
        target_category = (
            AssetCategory.objects.using(db_alias).filter(name=target_name).exclude(pk=category.pk).first()
        )

        if target_category is None:
            if category.name != target_name:
                category.name = target_name
                category.save(update_fields=["name"])
            continue

        for asset_type in AssetType.objects.using(db_alias).filter(category_id=category.pk):
            duplicate_type = AssetType.objects.using(db_alias).filter(
                category_id=target_category.pk,
                name=asset_type.name,
            ).first()
            if duplicate_type:
                Asset.objects.using(db_alias).filter(asset_type_id=asset_type.pk).update(
                    asset_type_id=duplicate_type.pk,
                    category_id=target_category.pk,
                )
                asset_type.delete()
            else:
                Asset.objects.using(db_alias).filter(asset_type_id=asset_type.pk).update(
                    category_id=target_category.pk
                )
                asset_type.category_id = target_category.pk
                asset_type.save(update_fields=["category"])

        Asset.objects.using(db_alias).filter(category_id=category.pk).update(category_id=target_category.pk)

        for attribute in AssetAttribute.objects.using(db_alias).filter(category_id=category.pk):
            duplicate_attribute = AssetAttribute.objects.using(db_alias).filter(
                category_id=target_category.pk,
                name=attribute.name,
            ).first()
            if duplicate_attribute:
                for value in AssetAttributeValue.objects.using(db_alias).filter(attribute_id=attribute.pk):
                    existing_value = AssetAttributeValue.objects.using(db_alias).filter(
                        asset_id=value.asset_id,
                        attribute_id=duplicate_attribute.pk,
                    ).exists()
                    if existing_value:
                        value.delete()
                    else:
                        value.attribute_id = duplicate_attribute.pk
                        value.save(update_fields=["attribute"])
                attribute.delete()
            else:
                attribute.category_id = target_category.pk
                attribute.save(update_fields=["category"])

        category.delete()

    for category_name in CANONICAL_CATEGORY_NAMES:
        AssetCategory.objects.using(db_alias).get_or_create(
            name=category_name,
            defaults={"description": ""},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_backfill_asset_depreciation_records'),
    ]

    operations = [
        migrations.RunPython(
            normalize_asset_categories,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(choices=[('Computers', 'Computers'), ('Networking', 'Networking'), ('Furniture', 'Furniture'), ('Printers', 'Printers'), ('Consumables', 'Consumables'), ('Projectors', 'Projectors'), ('Others', 'Others')], max_length=100, unique=True),
        ),
    ]
