# Generated by Django 6.0.2 on 2026-03-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_assetcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='condition_at_issue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='condition_at_return',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
