# Generated by Django 6.0.2 on 2026-03-15 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_assignment_assignees(apps, schema_editor):
    AssetAssignment = apps.get_model("assets", "AssetAssignment")
    db_alias = schema_editor.connection.alias

    for assignment in AssetAssignment.objects.using(db_alias).select_related("user"):
        user = assignment.user
        updated_fields = []

        if not assignment.assignee_identifier and user is not None:
            assignment.assignee_identifier = str(user.pk)
            updated_fields.append("assignee_identifier")
        if not assignment.assignee_name and user is not None:
            full_name = f"{user.first_name} {user.last_name}".strip()
            assignment.assignee_name = full_name or user.email
            updated_fields.append("assignee_name")
        if not assignment.assignee_contact and user is not None:
            assignment.assignee_contact = user.email
            updated_fields.append("assignee_contact")

        if updated_fields:
            assignment.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assetassignment_condition_at_issue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='assignee_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assignee_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_assignment_assignees, migrations.RunPython.noop),
    ]
