# Generated by Django 6.0.2 on 2026-04-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assetassignment_assignee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdepreciation',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='End-of-Life Value'),
        ),
    ]
