# Generated by Django 6.0.2 on 2026-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_assetdepreciation_salvage_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='is_computer_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
