# Generated by Django 6.0.2 on 2026-06-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_fix_computer_category_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='purchase',
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.DeleteModel(
            name='AssetPurchase',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
