# Generated by Django 6.0.2 on 2026-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('HELP_DESK', 'Help Desk Officer'), ('TECHNICIAN', 'ICT Technician'), ('DEPARTMENT_USER', 'Department User'), ('MANAGEMENT', 'Management Viewer')], default='DEPARTMENT_USER', max_length=20),
        ),
    ]
