"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bk2v%qzc=r4xn^-@2=2bziaw-1ggy0!7jcsa@(+d1+xr#2z8(^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "[::1]",
    "DESKTOP-T7IA860",
    "10.10.2.129",
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap4',
    'widget_tweaks',
    
    # Local apps
    'accounts',
    'core',
    'assets',
    'checkouts',
    'tickets',
    'maintenance',
    'iot_monitoring',
    'notifications',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (for asset images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# CORS settings (for IoT devices)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
]

JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "ICT-MS",
    # Title on the login screen (19 chars max)
    "site_header": "ICT-MS",
    # Title on the brand (19 chars max)
    "site_brand": "ICT-MS",
    "site_logo": "logo.png",
    # Logo to use for login form
    "login_logo": "logo.png",
    #"custom_css": "css/admin_custom.css",
    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",
    # Relative path to a favicon for your site
    "site_icon": "assets/images/favicon.svg",
    # Welcome text on the login screen
    "welcome_sign": "WELCOME TO ICT MANAGEMENT SYSTEM",
    # Copyright on the footer
    "copyright": "ICT-MS",
    "user_avatar": None,
    "custom_css": "css/jazzmin-custom.css",
    "show_ui_builder": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.group": "fas fa-user-tag",
        "accounts": "fas fa-users",
        "accounts.user": "fas fa-user-shield",
        "accounts.department": "fas fa-building",
        "assets": "fas fa-boxes",
        "assets.asset": "fas fa-laptop",
        "assets.assetcategory": "fas fa-tags",
        "checkouts": "fas fa-people-carry",
        "checkouts.checkoutrequest": "fas fa-clipboard-check",
        "checkouts.gpslocation": "fas fa-map-marker-alt",
        "checkouts.geofencealert": "fas fa-bell",
        "checkouts.checkouthistory": "fas fa-history",
        "tickets": "fas fa-ticket-alt",
        "tickets.faultticket": "fas fa-exclamation-circle",
        "tickets.ticketcomment": "fas fa-comments",
        "tickets.ticketattachment": "fas fa-paperclip",
        "maintenance": "fas fa-tools",
        "maintenance.maintenancelog": "fas fa-wrench",
        "maintenance.maintenanceschedule": "fas fa-calendar-check",
        "iot_monitoring": "fas fa-microchip",
        "notifications": "fas fa-bell",
        "notifications.notification": "fas fa-envelope",
        "notifications.alert": "fas fa-exclamation-triangle",
        "reports": "fas fa-chart-line",
        "core": "fas fa-cubes",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar_small_text": False,
    "footer_small_text": False,
    "navbar_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "body_small_text": False,
    "footer_small_text": True,
    "navbar_small_text": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


EASY_SEND_SMS_ENABLED = _env_bool("EASY_SEND_SMS_ENABLED", default=False)
EASY_SEND_SMS_API_KEY = os.getenv("EASY_SEND_SMS_API_KEY") or os.getenv("EASYSENDSMS_API_KEY", "")
EASY_SEND_SMS_SENDER_ID = os.getenv("EASY_SEND_SMS_SENDER_ID", "")
EASY_SEND_SMS_BASE_URL = os.getenv(
    "EASY_SEND_SMS_BASE_URL",
    "https://restapi.easysendsms.app/v1/rest/sms/send",
)
EASY_SEND_SMS_TIMEOUT = int(os.getenv("EASY_SEND_SMS_TIMEOUT", "15"))
EASY_SEND_SMS_DEFAULT_COUNTRY_CODE = os.getenv("EASY_SEND_SMS_DEFAULT_COUNTRY_CODE", "")
