"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys

import dj_database_url
from decouple import AutoConfig
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = AutoConfig(search_path=BASE_DIR)
IS_TESTING = "test" in sys.argv


def _env_bool(name, default=False):
    value = env(name, default=None)
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=""):
    value = env(name, default=default)
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_list_first(*names, default=""):
    return [item.strip() for item in _env_first(*names, default=default).split(",") if item.strip()]


def _env_first(*names, default=""):
    for name in names:
        value = env(name, default="")
        if value:
            return value
    return default


def _append_unique(items, *values):
    for value in values:
        if value and value not in items:
            items.append(value)


def _env_host(name):
    value = env(name, default="").strip()
    if not value:
        return ""
    value = value.removeprefix("https://").removeprefix("http://")
    return value.split("/", 1)[0]


def _database_url_needs_ssl(database_url):
    return not database_url.lower().startswith("sqlite")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

RUNNING_ON_VERCEL = _env_bool("VERCEL", default=False) or bool(env("VERCEL_ENV", default=""))
RUNNING_ON_RAILWAY = bool(
    _env_first(
        "RAILWAY_ENVIRONMENT",
        "RAILWAY_ENVIRONMENT_NAME",
        "RAILWAY_ENVIRONMENT_ID",
        "RAILWAY_PROJECT_ID",
        "RAILWAY_SERVICE_ID",
        "RAILWAY_DEPLOYMENT_ID",
        "RAILWAY_PUBLIC_DOMAIN",
        "RAILWAY_PRIVATE_DOMAIN",
    )
)
IS_DEPLOYED = RUNNING_ON_VERCEL or RUNNING_ON_RAILWAY

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env_first(
    "DJANGO_SECRET_KEY",
    "SECRET_KEY",
    "SECRETE_KEY",
)
if IS_DEPLOYED and not SECRET_KEY:
    raise ImproperlyConfigured(
        "Set SECRET_KEY or DJANGO_SECRET_KEY in your deployment environment variables."
    )
if not SECRET_KEY:
    SECRET_KEY = "django-insecure-bk2v%qzc=r4xn^-@2=2bziaw-1ggy0!7jcsa@(+d1+xr#2z8(^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=_env_bool("DEBUG", default=not IS_DEPLOYED))

ALLOWED_HOSTS = _env_list_first(
    "DJANGO_ALLOWED_HOSTS",
    "ALLOWED_HOSTS",
    default=(
        "127.0.0.1,"
        "localhost,"
        "ictms-production.up.railway.app,"
        ".up.railway.app,"
        "ict-ms.vercel.app,"
        "ict-8zpvb95rg-ws-teams.vercel.app,"
        ".vercel.app,"
        "[::1],"
        "DESKTOP-T7IA860,"
        "10.10.2.129,"
        "ictms.kabashug.com,"
        "www.ictms.kabashug.com"
    ),
)

VERCEL_HOSTS = [
    host
    for host in (
        _env_host("VERCEL_URL"),
        _env_host("VERCEL_BRANCH_URL"),
        _env_host("VERCEL_PROJECT_PRODUCTION_URL"),
    )
    if host
]
CSRF_TRUSTED_ORIGINS = _env_list_first(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "CSRF_TRUSTED_ORIGINS",
    default=(
        "https://ict-ms.vercel.app,"
        "https://*.vercel.app,"
        "https://ictms.kabashug.com,"
        "https://www.ictms.kabashug.com"
    ),
)
RAILWAY_HOSTS = [
    host
    for host in (
        "ictms-production.up.railway.app",
        ".up.railway.app",
        _env_host("RAILWAY_PUBLIC_DOMAIN"),
        _env_host("RAILWAY_STATIC_URL"),
    )
    if host
]
_append_unique(ALLOWED_HOSTS, *VERCEL_HOSTS, *RAILWAY_HOSTS)

CSRF_TRUSTED_ORIGINS = _env_list_first(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "CSRF_TRUSTED_ORIGINS",
    default=(
        "https://ict-ms.vercel.app,"
        "https://ict-8zpvb95rg-ws-teams.vercel.app,"
        "https://*.vercel.app,"
        "https://ictms-production.up.railway.app,"
        "https://*.up.railway.app,"
        "https://ictms.kabashug.com,"
        "https://www.ictms.kabashug.com"
    ),
)
_append_unique(
    CSRF_TRUSTED_ORIGINS,
    *(f"https://{host}" for host in VERCEL_HOSTS + RAILWAY_HOSTS if not host.startswith(".")),
)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap4',
    'widget_tweaks',
    
    # Local apps
    'accounts',
    'core',
    'assets',
    'checkouts',
    'tickets',
    'maintenance',
    'iot_monitoring',
    'notifications',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = _env_first(
    "DATABASE_URL",
    "POSTGRES_URL",
    "POSTGRES_URL_NON_POOLING",
    "POSTGRES_PRISMA_URL",
)

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=(
                _env_bool("DATABASE_SSL_REQUIRE", default=not DEBUG)
                if _database_url_needs_ssl(DATABASE_URL)
                else False
            ),
        )
    }
elif _env_first("POSTGRES_DATABASE", "POSTGRES_DB", "PGDATABASE"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _env_first("POSTGRES_DATABASE", "POSTGRES_DB", "PGDATABASE"),
            "USER": _env_first("POSTGRES_USER", "PGUSER"),
            "PASSWORD": _env_first("POSTGRES_PASSWORD", "PGPASSWORD"),
            "HOST": _env_first("POSTGRES_HOST", "PGHOST", default="localhost"),
            "PORT": _env_first("POSTGRES_PORT", "PGPORT", default="5432"),
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
        }
    }
elif IS_DEPLOYED:
    raise ImproperlyConfigured(
        "Set DATABASE_URL or POSTGRES_URL to a hosted database. "
        "SQLite cannot be used reliably in the serverless filesystem."
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if not DEBUG and not IS_TESTING
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Media files (for asset images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _env_bool(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=IS_DEPLOYED and not DEBUG,
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# CORS settings (for IoT devices)
CORS_ALLOWED_ORIGINS = _env_list(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default="http://localhost:8000",
)

JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "ICT-MS",
    # Title on the login screen (19 chars max)
    "site_header": "ICT-MS",
    # Title on the brand (19 chars max)
    "site_brand": "ICT-MS",
    "site_logo": "logo.png",
    # Logo to use for login form
    "login_logo": "logo.png",
    #"custom_css": "css/admin_custom.css",
    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",
    # Relative path to a favicon for your site
    "site_icon": "assets/images/favicon.svg",
    # Welcome text on the login screen
    "welcome_sign": "WELCOME TO ICT MANAGEMENT SYSTEM",
    # Copyright on the footer
    "copyright": "ICT-MS",
    "user_avatar": None,
    "custom_css": "css/jazzmin-custom.css",
    "show_ui_builder": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.group": "fas fa-user-tag",
        "accounts": "fas fa-users",
        "accounts.user": "fas fa-user-shield",
        "accounts.department": "fas fa-building",
        "assets": "fas fa-boxes",
        "assets.asset": "fas fa-laptop",
        "assets.assetcategory": "fas fa-tags",
        "checkouts": "fas fa-people-carry",
        "checkouts.checkoutrequest": "fas fa-clipboard-check",
        "checkouts.gpslocation": "fas fa-map-marker-alt",
        "checkouts.geofencealert": "fas fa-bell",
        "checkouts.checkouthistory": "fas fa-history",
        "tickets": "fas fa-ticket-alt",
        "tickets.faultticket": "fas fa-exclamation-circle",
        "tickets.ticketcomment": "fas fa-comments",
        "tickets.ticketattachment": "fas fa-paperclip",
        "maintenance": "fas fa-tools",
        "maintenance.maintenancelog": "fas fa-wrench",
        "maintenance.maintenanceschedule": "fas fa-calendar-check",
        "iot_monitoring": "fas fa-microchip",
        "notifications": "fas fa-bell",
        "notifications.notification": "fas fa-envelope",
        "notifications.alert": "fas fa-exclamation-triangle",
        "reports": "fas fa-chart-line",
        "core": "fas fa-cubes",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar_small_text": False,
    "footer_small_text": False,
    "navbar_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "body_small_text": False,
    "footer_small_text": True,
    "navbar_small_text": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}
EASY_SEND_SMS_ENABLED = _env_bool("EASY_SEND_SMS_ENABLED", default=False)
EASY_SEND_SMS_API_KEY = env("EASY_SEND_SMS_API_KEY", default="") or env(
    "EASYSENDSMS_API_KEY",
    default="",
)
EASY_SEND_SMS_SENDER_ID = env("EASY_SEND_SMS_SENDER_ID", default="")
EASY_SEND_SMS_BASE_URL = env(
    "EASY_SEND_SMS_BASE_URL",
    default="https://restapi.easysendsms.app/v1/rest/sms/send",
)
EASY_SEND_SMS_TIMEOUT = env("EASY_SEND_SMS_TIMEOUT", default=15, cast=int)
EASY_SEND_SMS_DEFAULT_COUNTRY_CODE = env(
    "EASY_SEND_SMS_DEFAULT_COUNTRY_CODE",
    default="",
)
