# Generated by Django 6.0.2 on 2026-04-20 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0010_assetassignment_assignee_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_devices', to='assets.asset')),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='GPSReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_readings', to='iot_monitoring.trackerdevice')),
            ],
            options={
                'ordering': ['-recorded_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='trackerdevice',
            index=models.Index(fields=['device_id'], name='iot_monitor_device__a7bd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackerdevice',
            index=models.Index(fields=['is_active'], name='iot_monitor_is_acti_3097c1_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsreading',
            index=models.Index(fields=['device', 'recorded_at'], name='iot_monitor_device__24faec_idx'),
        ),
    ]
