# Generated by Django 6.0.2 on 2026-03-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assetassignment_assignee_contact_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultticket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assets.location'),
        ),
    ]
