# Generated by Django 6.0.2 on 2026-03-16 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('assets', '0010_assetassignment_assignee_contact_and_more'),
        ('tickets', '0002_faultticket_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_summary', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('action_taken', models.TextField()),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket Resolution',
                'verbose_name_plural': 'Ticket Resolutions',
                'ordering': ['-resolved_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='faultticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='impact',
            field=models.CharField(choices=[('SINGLE_USER', 'Single User'), ('DEPARTMENT', 'Department'), ('ORGANIZATION_WIDE', 'Organization Wide')], default='SINGLE_USER', max_length=30),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='is_asset_fault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='requires_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='ticket_category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Fault'), ('SOFTWARE', 'Software Problem'), ('ACCOUNT', 'Account / Login'), ('NETWORK', 'Network Complaint'), ('REQUEST', 'ICT Service Request'), ('OTHER', 'Other ICT Support')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='triaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faultticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_USER', 'Pending User'), ('PENDING_PARTS', 'Pending Parts'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['due_date'], name='tickets_fau_due_dat_d876c2_idx'),
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['ticket_category'], name='tickets_fau_ticket__d9c1b5_idx'),
        ),
        migrations.AddField(
            model_name='ticketresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_resolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketresolution',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='tickets.faultticket'),
        ),
    ]
