# Generated by Django 6.0.2 on 2026-04-12 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('ASSIGNMENT_OVERDUE', 'Assignment Overdue')], max_length=40)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('notification_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notification_logs', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Notification Log',
                'verbose_name_plural': 'SMS Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'notification_date'], name='notificatio_event_t_e8968b_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_f73d42_idx'), models.Index(fields=['phone_number', 'notification_date'], name='notificatio_phone_n_ba888c_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_1b57f5_idx')],
            },
        ),
    ]
